=== NFDI4Culture/linked-open-exhibition/ausstellungen/exhibitions.dtd
<!-- exhibitions.dtd
     Document Type Definition for Linked Open Exhibition XML
     Aligned with the Exhibition Data Model (data-models/exhibition.csv)
     and Wikidata WikiProject Exhibitions property set.
     
     Required fields: qid, title, start_date
     Optional fields: all others
-->

<!ELEMENT exhibitions (exhibition+)>

<!ELEMENT exhibition (
  qid,
  wikidata_url,
  museum_url,
  slug,
  title,
  start_date,
  end_date,
  location,
  location_qid,
  curator,
  organizer,
  country,
  website,
  image,
  description
)>

<!-- Wikidata Q-identifier, e.g. Q138573075 -->
<!ELEMENT qid              (#PCDATA)>

<!-- Canonical Wikidata item URL -->
<!ELEMENT wikidata_url     (#PCDATA)>

<!-- Sprengel Museum website URL for the exhibition (P856 / P1 CIDOC) -->
<!ELEMENT museum_url       (#PCDATA)>

<!-- URL slug derived from museum_url -->
<!ELEMENT slug             (#PCDATA)>

<!-- Exhibition title (Wikidata P1476 / CIDOC P1_is_identified_by) -->
<!ELEMENT title            (#PCDATA)>

<!-- Start date ISO 8601 YYYY-MM-DD (Wikidata P580 / CIDOC P4_has_time-span) -->
<!ELEMENT start_date       (#PCDATA)>

<!-- End date ISO 8601 YYYY-MM-DD (Wikidata P582 / CIDOC P4_has_time-span) -->
<!ELEMENT end_date         (#PCDATA)>

<!-- Exhibition venue label (Wikidata P276 / CIDOC P7_took_place_at) -->
<!ELEMENT location         (#PCDATA)>

<!-- Wikidata Q-identifier for the venue -->
<!ELEMENT location_qid     (#PCDATA)>

<!-- Curator name (Wikidata P1640 / CIDOC P14_carried_out_by) -->
<!ELEMENT curator          (#PCDATA)>

<!-- Organizer name (Wikidata P664 / CIDOC P14_carried_out_by) -->
<!ELEMENT organizer        (#PCDATA)>

<!-- Country label (Wikidata P17 / CIDOC P7_took_place_at) -->
<!ELEMENT country          (#PCDATA)>

<!-- Official website URL (Wikidata P856) -->
<!ELEMENT website          (#PCDATA)>

<!-- Wikimedia Commons image URL (Wikidata P18) -->
<!ELEMENT image            (#PCDATA)>

<!-- Short English / German description of the exhibition -->
<!ELEMENT description      (#PCDATA)>

=== NFDI4Culture/linked-open-exhibition/ausstellungen/exhibitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE exhibitions SYSTEM "exhibitions.dtd">
<exhibitions>
  <exhibition>
    <qid>Q138547468</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138547468</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/aktuell/gabriela-jolowicz</museum_url>
    <slug>gabriela-jolowicz</slug>
    <title>Gabriela Jolowicz Holzschnitte - Woodcuts</title>
    <start_date>2026-01-21</start_date>
    <end_date>2026-05-26</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Stefan Gronert</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/aktuell/gabriela-jolowicz</website>
    <image/>
    <description>Gabriela Jolowicz woodcuts exhibition in the Sprengel Museum, Hanover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138572978</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138572978</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/archiv/fotografien-moderne</museum_url>
    <slug>fotografien-moderne</slug>
    <title>Fotografien Der Moderne Aus Der Sammlung</title>
    <start_date>2023-11-23</start_date>
    <end_date>2024-02-25</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Stefan Gronert</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/archiv/fotografien-moderne</website>
    <image/>
    <description>Fotografien Der Moderne Aus Der Sammlung, Ausstellung im Sprengel Museum, Hannover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138572994</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138572994</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/aktuell/abenteuer-abstraktion</museum_url>
    <slug>abenteuer-abstraktion</slug>
    <title>Abenteuer Abstraktion Von Der Moderne Bis Zur Gegenwart Sammlung</title>
    <start_date>2023-04-23</start_date>
    <end_date/>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Isabel Schulz</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/aktuell/abenteuer-abstraktion</website>
    <image/>
    <description>The Adventure of Abstraction. Exhibitions in Sprengel Museum Hannover 23.4.2023</description>
  </exhibition>
  <exhibition>
    <qid>Q138572988</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138572988</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/horst-antes</museum_url>
    <slug>horst-antes</slug>
    <title>EINE SAMMLUNG</title>
    <start_date>2026-04-11</start_date>
    <end_date>2026-07-05</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Reinhard Spieler</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/vorschau/horst-antes</website>
    <image/>
    <description>Eine Sammlung, Ausstellung im Sprengel Museum, Hannover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138772341</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138772341</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/kaloki-nyamai</museum_url>
    <slug>kaloki-nyamai</slug>
    <title>Kaloki Nyamai</title>
    <start_date>2025-04-11</start_date>
    <end_date>2025-07-05</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator/>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/vorschau/kaloki-nyamai</website>
    <image/>
    <description>exhibition at Sprengel Museum Hannover, 2025</description>
  </exhibition>
  <exhibition>
    <qid>Q138573058</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138573058</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/maja-zipf</museum_url>
    <slug>maja-zipf</slug>
    <title>EMOTIONAL SUPPORT OBJECTS - Hoping for Better Days</title>
    <start_date>2026-04-18</start_date>
    <end_date>2026-07-05</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Nora Niefanger</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/vorschau/maja-zipf</website>
    <image/>
    <description>Hoping for Better Days - EMOTIONAL SUPPORT OBJECTS, exhibition, Sprengel Museum,Hannover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138650553</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138650553</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/paul-sepuya</museum_url>
    <slug>paul-sepuya</slug>
    <title>PAUL MPAGI SEPUYAIN THE VIEW OF DESIRE</title>
    <start_date>2026-07-01</start_date>
    <end_date>2026-10-04</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Stefan Gronert</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/vorschau/paul-sepuya</website>
    <image/>
    <description>art exhibition at the Sprengel Museum, Hanover</description>
  </exhibition>
  <exhibition>
    <qid>Q138573096</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138573096</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/gleichmann</museum_url>
    <slug>gleichmann</slug>
    <title>Otto Gleichmann and Expressionism in Hanover</title>
    <start_date>2026-08-01</start_date>
    <end_date>2026-11-01</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator/>
    <organizer>Sprengel Museum</organizer>
    <country/>
    <website/>
    <image/>
    <description>art exhibition at the Sprengel Museum Hannover</description>
  </exhibition>
  <exhibition>
    <qid>Q138652613</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138652613</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/vorschau/aladag</museum_url>
    <slug>aladag</slug>
    <title>Nevin Aladağ</title>
    <start_date>2025-07-06</start_date>
    <end_date>2026-01-11</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator/>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/vorschau/aladag</website>
    <image/>
    <description>exhibition at Sprengel Museum Hannover</description>
  </exhibition>
  <exhibition>
    <qid>Q138638019</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138638019</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/archiv/sven-julien-kanclerski</museum_url>
    <slug>sven-julien-kanclerski</slug>
    <title>The Universal (Trumpets Starting to Play)</title>
    <start_date>2025-11-22</start_date>
    <end_date>2026-03-01</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator/>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/archiv/sven-julien-kanclerski</website>
    <image/>
    <description>Sven-Julien Kanclerski. The Universal (Trumpets Starting to Play), exhibition in Sprengel Museum, Hanover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138573028</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138573028</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/archiv/adrian-sauer-spectrum-stiftung</museum_url>
    <slug>adrian-sauer-spectrum-stiftung</slug>
    <title>Adrian Sauer: Truth Tablespectrum Internationaler Preis für Fotografie der Stiftung Niedersachsen</title>
    <start_date>2023-10-14</start_date>
    <end_date>2024-01-14</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Stefan Gronert</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/archiv/adrian-sauer-spectrum-stiftung</website>
    <image/>
    <description>Adrian Sauer: Truth Table exhibition in the Sprengel Museum, Hanover, 2026</description>
  </exhibition>
  <exhibition>
    <qid>Q138797847</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138797847</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/archiv/neuer-kunstclub2</museum_url>
    <slug>neuer-kunstclub2</slug>
    <title>NEUER KUNSTCLUB II</title>
    <start_date>2025-06-15</start_date>
    <end_date>2025-07-13</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator/>
    <organizer/>
    <country>Germany</country>
    <website>https://www.sprengel-museum.de/ausstellungen/archiv/neuer-kunstclub2</website>
    <image/>
    <description>Exhibition at Sprengel Museum Hannover, 2025</description>
  </exhibition>
  <exhibition>
    <qid>Q138573327</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138573327</wikidata_url>
    <museum_url>https://www.sprengel-museum.de/ausstellungen/archiv/feministische-avantgarde</museum_url>
    <slug>feministische-avantgarde</slug>
    <title>Stand Up! Feministische Avantgarde. Werke aus der Sammlung Verbund, Wien</title>
    <start_date>2025-07-05</start_date>
    <end_date>2025-09-28</end_date>
    <location>Sprengel Museum</location>
    <location_qid>Q510144</location_qid>
    <curator>Gabriele Schor</curator>
    <organizer/>
    <country/>
    <website>https://www.sprengel-museum.de/ausstellungen/archiv/feministische-avantgarde</website>
    <image/>
    <description>Exhibition at the Sprengel Museum showcasing the radical feminist art movement of the 1970s.</description>
  </exhibition>
  <exhibition>
    <qid>Q138651627</qid>
    <wikidata_url>https://www.wikidata.org/wiki/Q138651627</wikidata_url>
